### ISSUE TITLE
Units on statistics

### ISSUE THREAD

**Issue by hannahbrucemacdonald** [choderalab/freeenergyframework#10]
@dfhahn 

The plots currently have statistics written, whereas some of these don't have units associated (rho/R2)

Could we just remove the units for all statistics? I think they're not necessary if there are units on the axes?

![Screen Shot 2020-04-10 at 2 52 38 PM](https://user-images.githubusercontent.com/43652597/78995727-f19ae000-7b3a-11ea-92ae-2914597f7ef7.png)

**Comment by dfhahn** [comment]
Good point, thanks for finding this. I fixed it in the PR #11

**Comment by hannahbrucemacdonald** [comment]
Thanks!!
